In [75]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score,f1_score, confusion_matrix

In [3]:

data = pd.read_csv("D:\\proj\\data3\\airline_clnd.csv")

# Data Preparation

step in the machine learning process where we transform and refine the data based on our understanding from the data understanding phase. This involves making changes to the data to ensure it's suitable for modeling and analysis.

## Handling missing values

In [7]:
data.isna().sum()

SR                                     0
id                                     0
Gender                                 0
Customer_Type                          0
Age                                    0
Type_of_Travel                         0
Class                                  0
Flight_Distance                        0
Inflight_wifi_service                  0
Departure/Arrival_time_convenient      0
Ease_of_Online_booking                 0
Gate_location                          0
Food_and_drink                         0
Online_boarding                        0
Seat_comfort                           0
Inflight_entertainment                 0
On-board_service                       0
Leg_room_service                       0
Baggage_handling                       0
Checkin_service                        0
Inflight_service                       0
Cleanliness                            0
Departure_Delay_in_Minutes             0
Arrival_Delay_in_Minutes             310
satisfaction                           0
dtype: int64

In [8]:
data.dropna(inplace = True)

In [9]:
data.isna().sum().sum()

0

### Drop useless columns

In [11]:
data = data.drop(columns=['SR', 'id'])

## Data Transformation

## Data Encoding

### Qualitiave data to Quantitative data

Encode the categorical columns into numerical columns so that they can be used for analysis

### Techniques which can be followed 
* label encoding
* dummies (one hot coding)

We can use pandas to create dummies for each variable - Resultant columns will depend upon number of categories

In [18]:
data2 = data

In [19]:
pd.get_dummies(data2["Gender"])

        Female   Male
0        False   True
1        False   True
2         True  False
3         True  False
4        False   True
...        ...    ...
103899    True  False
103900   False   True
103901   False   True
103902    True  False
103903   False   True

[103594 rows x 2 columns]

In [23]:
categorical_cols = ['Gender', 'Customer_Type', 'Type_of_Travel', 'Class', 'satisfaction']

In [24]:
le = LabelEncoder()
for col in categorical_cols:
    data[col] = le.fit_transform(data[col])

In [25]:
data

,Gender,Customer_Type,Age,Type_of_Travel,Class,Flight_Distance,Inflight_wifi_service,Departure/Arrival_time_convenient,Ease_of_Online_booking,Gate_location,...,Inflight_entertainment,On-board_service,Leg_room_service,Baggage_handling,Checkin_service,Inflight_service,Cleanliness,Departure_Delay_in_Minutes,Arrival_Delay_in_Minutes,satisfaction
0,1,0,13,1,2,460,3,4,3,1,...,5,4,3,4,4,5,5,25,18.0,0
1,1,1,25,0,0,235,3,2,3,3,...,1,1,5,3,1,4,1,1,6.0,0
2,0,0,26,0,0,1142,2,2,2,2,...,5,4,3,4,4,4,5,0,0.0,1
3,0,0,25,0,0,562,2,5,5,5,...,2,2,5,3,1,4,2,11,9.0,0
4,1,0,61,0,0,214,3,3,3,3,...,3,3,4,4,3,3,3,0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103899,0,1,23,0,1,192,2,1,2,3,...,2,3,1,4,2,3,2,3,0.0,0
103900,1,0,49,0,0,2347,4,4,4,4,...,5,5,5,5,5,5,4,0,0.0,1
103901,1,1,30,0,0,1995,1,1,1,3,...,4,3,2,4,5,5,4,7,14.0,0
103902,0,1,22,0,1,1000,1,1,1,5,...,1,4,5,1,5,4,1,0,0.0,0
103903,1,0,27,0,0,1723,1,3,3,3,...,1,1,1,4,4,3,1,0,0.0,0

# Data Modeling

## First step is to split the data into training and testing

In [29]:
X = data.drop(columns=['satisfaction','Arrival_Delay_in_Minutes'])

In [30]:
y = data['satisfaction']

In [31]:
X

,Gender,Customer_Type,Age,Type_of_Travel,Class,Flight_Distance,Inflight_wifi_service,Departure/Arrival_time_convenient,Ease_of_Online_booking,Gate_location,...,Online_boarding,Seat_comfort,Inflight_entertainment,On-board_service,Leg_room_service,Baggage_handling,Checkin_service,Inflight_service,Cleanliness,Departure_Delay_in_Minutes
0,1,0,13,1,2,460,3,4,3,1,...,3,5,5,4,3,4,4,5,5,25
1,1,1,25,0,0,235,3,2,3,3,...,3,1,1,1,5,3,1,4,1,1
2,0,0,26,0,0,1142,2,2,2,2,...,5,5,5,4,3,4,4,4,5,0
3,0,0,25,0,0,562,2,5,5,5,...,2,2,2,2,5,3,1,4,2,11
4,1,0,61,0,0,214,3,3,3,3,...,5,5,3,3,4,4,3,3,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103899,0,1,23,0,1,192,2,1,2,3,...,2,2,2,3,1,4,2,3,2,3
103900,1,0,49,0,0,2347,4,4,4,4,...,4,5,5,5,5,5,5,5,4,0
103901,1,1,30,0,0,1995,1,1,1,3,...,1,5,4,3,2,4,5,5,4,7
103902,0,1,22,0,1,1000,1,1,1,5,...,1,1,1,4,5,1,5,4,1,0
103903,1,0,27,0,0,1723,1,3,3,3,...,1,1,1,1,1,4,4,3,1,0

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

* X_train represents all featres which will be given as an input 
* y_train will also be given as in input but as our target variable

In [34]:
X_train

,Gender,Customer_Type,Age,Type_of_Travel,Class,Flight_Distance,Inflight_wifi_service,Departure/Arrival_time_convenient,Ease_of_Online_booking,Gate_location,...,Online_boarding,Seat_comfort,Inflight_entertainment,On-board_service,Leg_room_service,Baggage_handling,Checkin_service,Inflight_service,Cleanliness,Departure_Delay_in_Minutes
18104,0,0,41,0,0,2660,3,3,3,3,...,5,5,2,2,2,2,3,2,4,0
66524,0,0,19,0,0,491,5,3,5,5,...,4,4,4,2,2,1,2,3,4,0
63076,1,0,29,0,0,2076,3,2,3,3,...,4,4,3,4,5,5,4,5,4,131
26315,1,0,52,0,0,2310,4,4,4,4,...,5,4,4,4,4,4,4,4,5,10
65647,1,0,54,0,0,685,1,1,1,1,...,5,5,5,5,5,5,3,5,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6281,0,0,61,1,2,458,4,5,4,2,...,4,4,1,1,4,1,3,1,5,0
55054,1,0,39,0,0,251,2,1,1,1,...,4,4,2,2,2,2,3,2,2,0
77048,0,1,34,0,0,1072,2,2,2,1,...,2,2,2,5,2,4,3,4,2,29
861,0,0,24,0,0,1013,3,3,3,3,...,3,3,3,1,1,2,2,2,3,25
15832,0,0,52,0,1,458,5,2,5,2,...,4,3,5,5,5,5,4,5,2,0

## 2nd step is to train the model

In [37]:
model = LogisticRegression(max_iter=10000)

In [38]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [39]:
model.coef_

array([[ 2.95655335e-02, -2.10789100e+00, -7.81242290e-03,
        -2.85399783e+00, -5.48323818e-01, -1.21941498e-05,
         3.92811390e-01, -1.17402578e-01, -1.34204075e-01,
         1.81446782e-02, -1.61993218e-02,  6.08824159e-01,
         7.29247352e-02,  5.61912732e-02,  3.04011759e-01,
         2.54560141e-01,  1.38365168e-01,  3.27676345e-01,
         1.26534021e-01,  2.17522749e-01, -4.52264676e-03]])

In [40]:
y_pred = model.predict(X_test)
y_pred

array([1, 0, 0, ..., 1, 0, 1])

In [123]:
new = data.iloc[1]
new = pd.DataFrame(new)
new = new.T

new = new.drop(columns = ["satisfaction","Arrival_Delay_in_Minutes"])
new

,Gender,Customer_Type,Age,Type_of_Travel,Class,Flight_Distance,Inflight_wifi_service,Departure/Arrival_time_convenient,Ease_of_Online_booking,Gate_location,...,Online_boarding,Seat_comfort,Inflight_entertainment,On-board_service,Leg_room_service,Baggage_handling,Checkin_service,Inflight_service,Cleanliness,Departure_Delay_in_Minutes
1,1.0,1.0,25.0,0.0,0.0,235.0,3.0,2.0,3.0,3.0,...,3.0,1.0,1.0,1.0,5.0,3.0,1.0,4.0,1.0,1.0

In [125]:
pred  =model.predict(new)
pred

array([0])

In [41]:
X_test

,Gender,Customer_Type,Age,Type_of_Travel,Class,Flight_Distance,Inflight_wifi_service,Departure/Arrival_time_convenient,Ease_of_Online_booking,Gate_location,...,Online_boarding,Seat_comfort,Inflight_entertainment,On-board_service,Leg_room_service,Baggage_handling,Checkin_service,Inflight_service,Cleanliness,Departure_Delay_in_Minutes
18595,0,0,66,0,1,326,5,2,2,2,...,4,1,5,5,5,5,2,5,3,0
19336,0,0,23,1,1,1142,2,4,2,5,...,2,1,1,4,3,4,4,5,1,0
72501,0,0,31,1,1,309,1,5,1,1,...,1,5,5,4,3,5,5,4,5,0
85210,0,0,50,0,1,794,3,3,3,3,...,3,3,3,3,3,3,2,3,2,94
87824,1,0,34,0,1,143,4,5,3,5,...,4,4,4,3,2,4,2,4,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13497,0,0,45,0,0,622,1,2,5,2,...,4,3,1,1,1,1,3,1,4,20
59583,1,0,36,0,0,2329,1,1,5,1,...,4,5,5,5,5,5,5,5,5,10
84966,1,0,69,0,0,488,3,3,3,3,...,4,1,4,4,4,4,2,4,4,2
44109,1,0,15,1,1,1062,3,4,3,3,...,3,3,3,3,3,4,4,4,3,0
43853,1,0,57,0,1,157,4,2,2,2,...,4,5,5,3,2,3,3,2,5,0

In [42]:
y_test

18595    1
19336    0
72501    0
85210    0
87824    1
        ..
13497    0
59583    1
84966    1
44109    0
43853    1
Name: satisfaction, Length: 20719, dtype: int32

# Evaluation

In [44]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:",f1)
print("Confusion Matrix:\n", confusion_mat)

Accuracy: 0.8735460205608379
Precision: 0.8733487833140209
Recall: 0.831531332744925
F1-score: 0.8519272069628122
Confusion Matrix:
 [[10562  1093]
 [ 1527  7537]]